before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}'
  main: cmd/uncover/uncover.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

snapcrafts:
  - id: uncover
    replacements:
      darwin: macOS
    name: uncover
    publish: false
    summary: Uncover is a go wrapper using APIs of well known search engines to quickly discover exposed hosts on the internet.
    description: |
      Uncover is a go wrapper using APIs of well known search engines to quickly discover exposed hosts on the internet. It is built with automation in mind, so you can query it and utilize the results with your current pipeline tools. Currently, it supports shodan, shodan-internetdb, censys, and fofa search API.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      uncover:
        command: uncover
        plugs:
          - home
          - network
          - removable-media
          - dot-uncover
    plugs:
      dot-uncover:
        interface: personal-files
        write:
          - $HOME/.config/uncover